### ISSUE TITLE
Bugs / improvements

### ISSUE THREAD

**Issue by panosnl** [zulufoxtrot/peerberry-robo-investor#2]
Thanks for the script. I started running it. waiting for loans to appear in peerberry now....

I noticed some oddities in the script that I changed for my use:

I see AMOUNT_TO_BUY is defined but not used to buy:
line 52:       `      api_client.purchase_loan(loan["loanId"], 10)`

I see there is a sold_out counter that triggers reloading loan list when number = 5
Then the amount of loans to load shoud be (available money/ amount to buy)+5 ; currently is is done by adding 20% margin which can be a problem is 20% < 5 loans

line 83: `        sold_out_counter = 0`
This resets the counter after every loan

Furthermore I added an extra filter to the loan list:
   `   min_available_amount=AMOUNT_TO_BUY,`

**Comment by zulufoxtrot** [comment]
>  api_client.purchase_loan(loan["loanId"], 10)

> min_available_amount=AMOUNT_TO_BUY,

Thanks, fixed/implemented.

> I see there is a sold_out counter that triggers reloading loan list when number = 5
Then the amount of loans to load shoud be (available money/ amount to buy)+5 ; currently is is done by adding 20% margin which can be a problem is 20% < 5 loans

I'm not sure I understand the reasoning here (but you may be right).
Here is the reason why I use a margin:
Loans get filled _fast_ on peerberry (they're usually all gone in a few minutes). On the other hand, the script has to wait at least 2 second between purchases to prevent rate limiting. This means some loans in my list will be filled before the scripts gets a chance to purchase them, even though they were available at the time the list was made. So it attempts to purchase more than what it can afford.

Can you maybe explain the problem with a step-by-step example?

> This resets the counter after every loan

I believe there is a logical reason for this... but it's Friday afternoon and my brain is melting 😅

**Comment by panosnl** [comment]
> Can you maybe explain the problem with a step-by-step example?

50 EUR balance, 10 eur per loan
20% rule gets 6 loans. So when 2, 3 or 4 loans are sold out then not enough loans will be bougth.  Also a rescan will not be triggered 

1000 Eur balance, 10 eur per loan,
20% will get 120 loans. However at 5 sold out loans a rescan will be triggered meaning the max number of loans to be processed will be 105. scanning more is not a problem but not needed

With long loan lists rescanning is indeed recommended since I see the loans disappearing rapidly.
Are you sure rescanning is triggered. Code seems to reset counter after every buy it seems but I might be mistaken. Friday here too....

**Comment by panosnl** [comment]
This script is great! saves me a lot of time....

Some remarks:

>> This resets the counter after every loan
>
>I believe there is a logical reason for this... but it's Friday afternoon and my brain is melting 😅

You were right. Your reset counter triggers on 5 subsequent 'sold outs' and resets after a successful buy..

However, rescanning the loan list within a for loop does not update the list used for this loop, so it conintues with the old list.. (I checked with the Python documentation)

Yesterday I had quite some loans to fill >100. Soon the loan list was resulting 'sold outs'. After 5 sold outs in a row the rescan was triggered but it kept continuing the the old list resulting in many sold out warnings and rescan messages. 

I changed the code to break after a sold out trigger and re-running the for-loop with the new list...

Also since you cannot buy a loan that leaves less than 10 EUR remaining so added that to the
`min_available_amount=AMOUNT_TO_BUY + 10,`

Futhermore I encountered a bug. min should be max:
line 30:`    if not available_balance >= min(10, AMOUNT_TO_BUY):`
I changed it so it will still buy if cash is  10 < balance < AMOUNT_TO_BUY

```import logging
import os
import sys
import time
from logging.handlers import RotatingFileHandler

from peerberrypy import API
from peerberrypy.exceptions import InsufficientFunds

if __name__ == "__main__":

    # amount in EUR to allocate to each loan
    AMOUNT_TO_BUY = 20

    logging.basicConfig(
        handlers=[RotatingFileHandler('log.txt', maxBytes=100000, backupCount=10),
                  logging.StreamHandler()],
        level=logging.INFO,
        format="[%(asctime)s] %(levelname)s %(message)s",
        datefmt='%Y-%m-%dT%H:%M:%S')

    api_client = API(
        email=os.environ['PEERBERRY_EMAIL'],
        password=os.environ['PEERBERRY_PASSWORD'],
    )
    logging.info("Logged in.")

    available_balance = api_client.get_overview()["availableMoney"]
    logging.info(f"Available balance: {available_balance}€")

    if not available_balance >= 10:
        logging.info("Available balance below 10€. Aborting.")
        api_client.logout()
        logging.info("Logged out.")
        sys.exit()
    elif not available_balance >= AMOUNT_TO_BUY:
        AMOUNT_TO_BUY = available_balance    
        logging.info("Available balance below the purchase amount. Purchase amount adjusted.")
    elif not available_balance > AMOUNT_TO_BUY +10:
        AMOUNT_TO_BUY = available_balance    
        logging.info("Available balance just above the purchase amount. Purchase amount adjusted.")
        
        
            
    # take a 20% margin (some loans will become unavailable for purchase by the time we try to purchase them)
    loans_needed = int(available_balance * 1.2// AMOUNT_TO_BUY) + 10 

    loans = api_client.get_loans(min_interest_rate=9,
                                 max_remaining_term=60,
                                 group_guarantee=True,
                                 exclude_invested_loans=True,
                                 sort="interest_rate",
                                 quantity=loans_needed,
                                 min_available_amount=AMOUNT_TO_BUY + 10,
                                 raw=True)

    logging.info(f"Found {len(loans)} loans matching criteria (max requested: {loans_needed})")
    
    rescan = 0
    sold_out_counter = 0
    if len(loans) == 0:
       script_done = 1
    else:
       script_done = 0

    while script_done == 0:
        for loan in loans:
            logging.info(f"Purchasing #" + str(loan["loanId"]))
            try:
                api_client.purchase_loan(loan["loanId"], AMOUNT_TO_BUY)
            # except TooManyRequestsException:
            # uncomment this once exception handling has been improved in the library
            # no real need anyway, spacing purchases by 2 seconds does not trigger rate limiting.
            #     logging.error("Too many API requests. Sleeping for 1 minute, then resuming purchases")
            #     time.sleep(60)
            #     logging.info("Resuming...")
            #     continue
            except InsufficientFunds as e:
                if str(e) == "Low investor balance":
                    logging.info("Out of funds. Ending purchases.")
                    break
                if str(e) == "The loan is sold out":
                    sold_out_counter += 1
                if sold_out_counter >= 5:
                    logging.info("Too many sold out loans, refreshing list...")
                    loans = api_client.get_loans(min_interest_rate=9,
                                                 max_remaining_term=60,
                                                 group_guarantee=True,
                                                 exclude_invested_loans=True,
                                                 sort="interest_rate",
                                                 quantity=loans_needed,
                                                 min_available_amount=AMOUNT_TO_BUY + 10,
                                                 raw=True)
                    sold_out_counter = 0
                    rescan = 1
                    break
                if str(e) == "Something wrong! Wait a minute and try please again":
                    logging.info("wait 5 sec")
                    time.sleep(5)
                # other known cases:
                # - The remaining available loan amount after investment cannot be less than the minimum investment amount
                # - The loan is sold out
                # - Something wrong! Wait a minute and try please again
                logging.info("Failed buying, skipping")
                logging.info(f"Error message: {e}")
                time.sleep(2)
                continue

            sold_out_counter = 0
            time.sleep(2)
                       
        if rescan == 1:
            rescan = 0
            script_done = 0
        else:
            script_done = 1

    api_client.logout()
    logging.info("Logged out.")
```
